# Generated by Django 5.1.2 on 2024-11-04 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='page_images/', verbose_name='Изображение')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'изображение страницы',
                'verbose_name_plural': 'Изображения страниц',
                'ordering': ['-date_uploaded'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icons/', verbose_name='Иконка')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('is_public', models.BooleanField(default=False, verbose_name='Опубликована')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Контент')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')),
                ('previous', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.page', verbose_name='Предыдущая страница')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('images', models.ManyToManyField(blank=True, null=True, to='main.pageimage', verbose_name='Изображения')),
            ],
            options={
                'verbose_name': 'страница',
                'verbose_name_plural': 'Страницы',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50, verbose_name='Никнейм')),
                ('photo', models.ImageField(upload_to='profile_photos/', verbose_name='Фото')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'профиль',
                'verbose_name_plural': 'Профили',
                'ordering': ['-date_created'],
            },
        ),
    ]
