# Generated by Django 5.1.2 on 2024-11-04 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='images',
            field=models.ManyToManyField(blank=True, to='main.pageimage', verbose_name='Изображения'),
        ),
    ]
