# Generated by Django 5.1.2 on 2024-11-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_page_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Контент'),
        ),
    ]
